apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v61h2ay7l-python
  janus-idp.io/tekton: v61h2ay7l-python
  backstage.io/kubernetes-id: v61h2ay7l-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v61h2ay7l-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
