apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v61h2ay7l-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v61h2ay7l-python 
  name: v61h2ay7l-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v61h2ay7l-python 
